apiVersion: v1
kind: Pod
metadata:
  name: dummy-test
spec:
  containers:
    image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - {key: environment, operator: In, values: [pre, dev]}